---
- name: AI/ML Fabric Create
  gather_facts: false
  hosts:
    - ndfc
  tasks:
    - name: Create VRFs
      cisco.dcnm.dcnm_vrf:
        fabric: AMS-CML-VXLAN
        state: merged
        config:
          - vrf_name: ml_workloads
            vrf_template: Default_VRF_Universal
            vrf_extension_template: Default_VRF_Extension_Universal

    - name: Create Networks
      cisco.dcnm.dcnm_network:
        fabric: AMS-CML-VXLAN
        state: merged
        config:
          - net_name: ml_app_1
            vrf_name: ml_workloads
            net_id: 202301
            net_template: Default_Network_Universal
            net_extension_template: Default_Network_Extension_Universal
            vlan_id: 2301
            gw_ip_subnet: '172.25.101.254/24'
            attach:
              - ip_address: 172.16.254.179
                ports: [Port-Channel3]
              - ip_address: 172.16.254.180
                ports: [Port-Channel3]
            deploy: true
          - net_name: roce_traffic
            vrf_name: ml_workloads
            net_id: 202300
            net_template: Default_Network_Universal
            net_extension_template: Default_Network_Extension_Universal
            vlan_id: 2300
            gw_ip_subnet: '172.25.100.254/24'
            attach:
              - ip_address: 172.16.254.181
                ports: [Ethernet1/3]
            deploy: true
